version: "2"

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 40 # Default 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2,phpcs.xml"

  sonar-php:
    enabled: true
    checks:
      php:S1192: # Define a constant instead of duplicating this literal "value" X times.
        enabled: false
      php:S1117: # Rename variable which has the same name as the class property.
        enabled: false
      php:S1142: # Too many return statements.
        enabled: false

  phpmd:
    enabled: true
    config:
      rulesets: "cleancode,codesize,controversial,design,unusedcode,PHPMDRuleset.xml"
    checks:
      CleanCode/StaticAccess:
        enabled: false
